[package]
name = "dnf_login"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rsa = "0.6.1"
rand = "0.8.5"
base64 = "0.13.0"
hex = "0.4.3"
mysql = "22.1.0"
md5 = "0.7.0"